# Generated by Django 2.0.7 on 2018-08-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plusminus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='fga',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='fgm',
            field=models.IntegerField(default=0),
        ),
    ]
