# Generated by Django 2.0.7 on 2018-08-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plusminus', '0002_auto_20180812_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='stats',
            name='fgp',
            field=models.IntegerField(default=0),
        ),
    ]
