# Generated by Django 2.0.7 on 2018-08-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plusminus', '0003_auto_20180812_1748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
        migrations.AddField(
            model_name='player',
            name='fga',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='fgm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='fgp',
            field=models.IntegerField(default=0),
        ),
    ]
